"""Train 168h regression models from an existing CSV.

Expected configurable columns are discovered from the dataset; pass exact columns
with --x0, --x24 and --y168. No dataset is generated by this script.
"""
import argparse
import sys
from pathlib import Path
import pandas as pd

# Permit `python training/train_drift.py ...` from the backend root.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from sklearn.model_selection import GroupShuffleSplit
from backend.ml.drift.predictor import DriftPredictor

def main():
    p=argparse.ArgumentParser()
    p.add_argument("--csv",required=True); p.add_argument("--x0",required=True)
    p.add_argument("--x24",required=True); p.add_argument("--y168",required=True)
    p.add_argument("--group",default=None); p.add_argument("--out",default="models/drift.joblib")
    a=p.parse_args()
    df=pd.read_csv(a.csv).dropna(subset=[a.x0,a.x24,a.y168])
    X=df[[a.x0,a.x24]].astype(float); y=df[a.y168].astype(float)
    # Model comparison is performed on the supplied existing data. For production,
    # replace with a temporal/group-aware holdout before selecting the final model.
    model=DriftPredictor(); metrics=model.fit_compare(X,y); model.save(a.out)
    print(metrics)

if __name__=="__main__": main()
