/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellAnalysisRouteImport } from './routes/_shell.analysis'
import { Route as ShellLotsRouteImport } from './routes/_shell.lots'
import { Route as ShellOverviewRouteImport } from './routes/_shell.overview'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellComponentsIndexRouteImport } from './routes/_shell.components.index'
import { Route as ShellComponentsComponentIdRouteImport } from './routes/_shell.components.$componentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAnalysisRoute = ShellAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLotsRoute = ShellLotsRouteImport.update({
  id: '/lots',
  path: '/lots',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOverviewRoute = ShellOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellComponentsIndexRoute = ShellComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellComponentsComponentIdRoute =
  ShellComponentsComponentIdRouteImport.update({
    id: '/components/$componentId',
    path: '/components/$componentId',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof ShellAnalysisRoute
  '/lots': typeof ShellLotsRoute
  '/overview': typeof ShellOverviewRoute
  '/settings': typeof ShellSettingsRoute
  '/components/$componentId': typeof ShellComponentsComponentIdRoute
  '/components/': typeof ShellComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof ShellAnalysisRoute
  '/lots': typeof ShellLotsRoute
  '/overview': typeof ShellOverviewRoute
  '/settings': typeof ShellSettingsRoute
  '/components/$componentId': typeof ShellComponentsComponentIdRoute
  '/components': typeof ShellComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/analysis': typeof ShellAnalysisRoute
  '/_shell/lots': typeof ShellLotsRoute
  '/_shell/overview': typeof ShellOverviewRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/components/$componentId': typeof ShellComponentsComponentIdRoute
  '/_shell/components/': typeof ShellComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/lots'
    | '/overview'
    | '/settings'
    | '/components/$componentId'
    | '/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/lots'
    | '/overview'
    | '/settings'
    | '/components/$componentId'
    | '/components'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/analysis'
    | '/_shell/lots'
    | '/_shell/overview'
    | '/_shell/settings'
    | '/_shell/components/$componentId'
    | '/_shell/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/analysis': {
      id: '/_shell/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof ShellAnalysisRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/lots': {
      id: '/_shell/lots'
      path: '/lots'
      fullPath: '/lots'
      preLoaderRoute: typeof ShellLotsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/overview': {
      id: '/_shell/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof ShellOverviewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/components/': {
      id: '/_shell/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ShellComponentsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/components/$componentId': {
      id: '/_shell/components/$componentId'
      path: '/components/$componentId'
      fullPath: '/components/$componentId'
      preLoaderRoute: typeof ShellComponentsComponentIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAnalysisRoute: typeof ShellAnalysisRoute
  ShellLotsRoute: typeof ShellLotsRoute
  ShellOverviewRoute: typeof ShellOverviewRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellComponentsComponentIdRoute: typeof ShellComponentsComponentIdRoute
  ShellComponentsIndexRoute: typeof ShellComponentsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAnalysisRoute: ShellAnalysisRoute,
  ShellLotsRoute: ShellLotsRoute,
  ShellOverviewRoute: ShellOverviewRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellComponentsComponentIdRoute: ShellComponentsComponentIdRoute,
  ShellComponentsIndexRoute: ShellComponentsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
